name: citibike_sdss
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11
  - pip
  - click
  - python-dotenv>=0.5.1 
  - geopandas
  - requests
  - beautifulsoup4
  - ipykernel
  - cenpy
  - qgis=3.30.2
