#! /usr/bin/bash

# All values are in feet
COARSE_RES=1000
MEDIUM_RES=100
MEDIUM_CELL_AREA=$(($MEDIUM_RES**2))
FINE_RES=10
FINE_CELL_AREA=$(($FINE_RES**2))
WALK_RADIUS=2640
MAX_DIST_CB_TO_STREET=60
MIN_DIST_CB_TO_CB=100
